config/routes.rb
Rails.application.routes.draw do
  resources 'users' do
    member do
      get :following, :followers, :favorites
    end
  end
  resources 'favorite_relations', only: [:create, :destroy]
  resources 'sessions', only: [:new, :create, :destroy]
  resources 'tweets' do
    member do
      get :favorites, :reply
    end
  end
  resources 'relationships', only: [:create, :destroy]

  root 'static_pages#home'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/search', to: 'tweets#search', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @user = current_user
      @tweet = current_user.tweets.build
      @feed_items = current_user.feed.paginate(params[:page])
    end
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<h1>Help page</h1>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="col-md-4 sidebar-nav fix">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/tweet_form' %>
      </section>
    </aside>
  <div class="col-md-8">
    <h3 class>Timeline</h3>
    <%= render 'shared/feed' %>
  </div>
</div>
<% else %>
  <div class="hero-unit">
    <h1 class="center">welcome to katatter</h1>
    <div class="col-md-4">

    <h3>ログイン</h3>

    <%= form_for(:session, url: sessions_path) do |f| %>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email, size: 30 %>
      <%= f.label :password %>
      <%= f.password_field :password, size: 30 %>
    </div>
      <%= f.submit 'ログイン' , class: "btn btn-primary"%>
    <% end %>
    </div>
    <br>
    <p>
    ユーザー登録をして今から始める!
    <%= link_to "ユーザ登録する", signup_path, class:"btn btn-large btn-primary" %>
    </p>
  </div>
<% end %>