config/routes.rb
Rails.application.routes.draw do
  resources 'users' do
    member do
      get :following, :followers, :favorites
    end
  end
  resources 'favorite_relations', only: [:create, :destroy]
  resources 'sessions', only: [:new, :create, :destroy]
  resources 'tweets' do
    member do
      get :favorites, :reply
    end
  end
  resources 'relationships', only: [:create, :destroy]

  root 'static_pages#home'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/search', to: 'tweets#search', via: 'get'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :reverse_favorite_relations, foreign_key: "favorite_tweet_id", class_name: "FavoriteRelation", dependent: :destroy
  has_many :user_favorites, through: :reverse_favorite_relations, source: :user_favorite
  # has_many :reply_relations, foreign_key: "replied_tweet_id", dependent: :destroy
  # has_many :replied_tweets, through: :reply_relations, class_name: "Tweet", source: :replied_tweet
  # has_many :reverse_reply_relations, foreign_key: "reply_tweet_id", class_name: "ReplyRelation", dependent: :destroy
  # has_many :reply_tweets, through: :reverse_reply_relations, class_name: "Tweet", source: :reply_tweet
  #
  # accepts_nested_attributes_for :reply_relations

  default_scope -> { order('created_at DESC') }

  mount_uploader :image

  validates  :tubuyaki,
    length: { maximum: 255 },
    presence: true

  validates :user_id,
    presence: true

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", user_id: user)
  end

  def reply!(other_tweet)
    reply_relations.create!( replied_tweet_id: other_tweet.id )
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @user = current_user
    @tweet = @user.tweets.build(tweet_params)
    if @tweet.save
      flash[:success] = "Tweeted!"
      redirect_to(:back)
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @tweet.destroy
    redirect_to root_url
  end

  def index
    @search = Tweet.search(params[:q])
    @tweets = @search.result.paginate(params[:page])
    respond_to do |format|
      format.html
      format.json { render json: @topics }
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @reply_tweets = Tweet.reorder(created_at: :asc).where(replied_tweet_id: params[:id])
  end

  def favorites
    @title = "お気に入りしたユーザー"
    @tweet = Tweet.find(params[:id])
    @users = @tweet.user_favorites.paginate(params[:page])
  end

  def  reply
    @tweet = Tweet.find(params[:id])
    @reply_tweets = Tweet.reorder(created_at: :asc).where(replied_tweet_id: params[:id])
    @tweet = Tweet.new
  end


  private

  def tweet_params
    params.require(:tweet).permit(:tubuyaki, :id, :user_id, :image, :image_cache, :remove_image, :replied_tweet_id)
  end

  def correct_user
    @tweet = current_user.tweets.find_by(id: params[:id])
    redirect_to root_url if @tweet.nil?
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def wrap(tubuyaki)
   sanitize(raw(tubuyaki.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  # def
  #
  # end

  def self.reply!(other_tweet)
    self.reply_relations.create!( replied_tweet_id: other_tweet.id )
  end
  # @reply_tweets = Tweet.reorder(created_at: :asc).where(replied_tweet_id: params[:id])

  def reply_tweets(tweet)
    @replytweets = Tweet.where(replied_tweet_id: tweet.id)
  end

 private

   def wrap_long_string(text, max_width = 30)
     zero_width_space = "&#8203;"
     regex = /.{1,#{max_width}}/
     (text.length < max_width) ? text :
                                 text.scan(regex).join(zero_width_space)
   end


   def tweet_params
     params.require(:tweet).permit(:tubuyaki, :id, :user_id, :image, :image_cache, :remove_image)
   end
end

app/views/tweets/_tweet.html.erb
<li id="<%= tweet.id %>">
  <a href="<%= tweet_path(tweet.id) %>">
    <div>
      <% if tweet.user.image? %>
      <%= image_tag tweet.user.image.url(:thumb) %>
      <% else %>
      <%= image_tag("egg.png", width: "50", height: "50") %>
      <% end %>
    </div>
    <span class="user">
      <%= link_to tweet.user.name, tweet.user %> <small> <%= tweet.user.userid %> </small>
    </span><br>
    <span class="tubuyaki"><%= wrap(simple_format(tweet.tubuyaki)) %></span><br>
    <span class="timestamp">
      <small>Tweeted <%= time_ago_in_words(tweet.created_at) %> ago.</small>
    </span>

    <% if current_user?(tweet.user) %>
      <%= link_to "消す", tweet, method: :delete, data: { confirm: "本当に消しますか？"}, title: tweet.tubuyaki %><br>
    <div class="favorite-star">
      ☆: <%= link_to "#{ tweet.user_favorites.count }", favorites_tweet_path(tweet.id) %>
    </div>
    <% else %>
      <% if current_user.favorite?(tweet) %>
        <%= form_for(current_user.favorite_relations.find_by(favorite_tweet_id: tweet.id), html: { method: :delete } ) do |f| %>
        <%= f.submit "★", class: "btn btn-primary btn-sm" %>：
        <%= link_to "#{ tweet.user_favorites.count }", favorites_tweet_path(tweet.id) %>
        <% end %>
      <% else %>
        <%= form_for(current_user.favorite_relations.build(favorite_tweet_id: tweet.id)) do |f| %>
        <div> <%= f.hidden_field :favorite_tweet_id %> </div>
          <%= f.submit "☆", class: "btn btn-primary btn-sm" %>：
          <%= link_to "#{ tweet.user_favorites.count }", favorites_tweet_path(tweet.id) %>

        <% end %>
      <% end %>
    <% end %>
    <!-- <%= link_to "#{ tweet.user_favorites.count }", favorites_tweet_path(tweet.id) %> -->
    <%= link_to "リプライ", reply_tweet_path(tweet.id), class: "btn btn-primary" %>：
    <%= link_to reply_tweets(tweet).count, reply_tweet_path(tweet.id) %>
  </a>
</li>

app/views/tweets/create.js.erb
$("#timeline").html('<%= render partial: '/tweets/tweet', collection: @tweets %>')

app/views/tweets/favorites.html.erb
<div class="row">
  <div class="col-md-4">
    <% if @tweet.user.image? %>
    <%= image_tag @tweet.user.image.url(:thumb) %>
    <% else %>
    <%= image_tag("egg.png", width: "50", height: "50")  %>
    <% end %>
  </div>

  <div class="col-md-8">
    <span class="user">
      <%= link_to @tweet.user.name, @tweet.user %>
      <small><%= @tweet.user.userid %></small>
    </span>
    <span class="tubuyaki">
      <%= wrap(simple_format(@tweet.tubuyaki)) %>
    </span><br>
    <span class="timestamp">
      <small>Tweeted <%= time_ago_in_words(@tweet.created_at) %> ago.</small>
    </span>
    <% unless @tweet.image.to_s.empty? %>
    <span>
      <%= image_tag @tweet.image.url  %>
    </span>
    <% end %>
    <% if current_user?(@tweet.user) %>
      <%= link_to "消す", @tweet, method: :delete, data: { confirm: "本当に消しますか？"}, title: @tweet.tubuyaki %>
    <% else %>
      <% if current_user.favorite?(@tweet) %>
        <%= form_for(current_user.favorite_relations.find_by(favorite_tweet_id: @tweet.id), html: { method: :delete } ) do |f| %>
        <%= f.submit "★", class: "btn btn-primary" %>
        <% end %>
      <% else %>
        <%= form_for(current_user.favorite_relations.build(favorite_tweet_id: @tweet.id)) do |f| %>
        <div> <%= f.hidden_field :favorite_tweet_id %> </div>
          <%= f.submit "☆", class: "btn  btn-primary" %>
        <% end %>
      <% end %>
    <% end %>
    <div class="col-md-8">
        <span>お気に入りしたユーザー</span>
    <% @users.each do |user| %>
    <ul class="users">
      <%= render user %>
    </ul>
    <% end %>
    </div>
</div>

app/views/tweets/index.html.erb
<h2>ツイートを探す</h2>
<%= search_form_for @search do |f| %>
  <%= f.label :tubuyaki_cont, "ことば" %>
  <%= f.text_field :tubuyaki_cont %>
  <div class="action">
    <%= f.submit 'さがす' %>
  </div>
<% end %>

<%= will_paginate %>
<% @tweets.each do |tweet| %>
  <ul class="tweets">
    <%= render tweet %>
  </ul>
<% end %>
<%= will_paginate %>

app/views/tweets/reply.html.erb
<% @replied_tweet = Tweet.find(params[:id]) %>
<div class="tweets">
<%= render @replied_tweet %>
</div>
<%= form_for(@tweet) do |f| %>
  <div class="field">
    <%= f.text_area :tubuyaki, default: "#{@replied_tweet.user.userid}" %>
    <%= f.file_field :image %>
    <%= f.hidden_field :replied_tweet_id, value: "#{@replied_tweet.id}", readonly: true %>
  </div>
  <%= f.submit "Go", class: "btn btn-primary" %>
<% end %>
<div class="col-md-8">
  <% if @reply_tweets.any? %>
    <h2>リプライ</h2>
    <%= @reply_tweets.each do |tweet| %>
    <ul class="tweets">
      <%= render tweet %>
    </ul>
    <% end %>
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class="tweets">
<%= render @tweet %>
<% unless @tweet.image.to_s.empty? %>
<span>
  <%= image_tag @tweet.image.url  %>
</span>
<% end %>
</div>
<!-- <div class="row">
  <div class="col-md-4">
    <% if @tweet.user.image? %>
      <%= image_tag @tweet.user.image.url(:thumb) %>
    <% else %>
      <%= image_tag("egg.png", width: "50", height: "50")  %>
    <% end %>
    <span class="user">
      <%= link_to @tweet.user.name, @tweet.user %>
      <small><%= @tweet.user.userid %></small>
    </span>
    <span class="tubuyaki">
      <%= wrap(simple_format(@tweet.tubuyaki)) %>
    </span><br>
    <span class="timestamp">
      <small>Tweeted <%= time_ago_in_words(@tweet.created_at) %> ago.</small>
    </span>

    <div class="row">

    <% if current_user?(@tweet.user) %>
    <div class="col-md-1">
      <%= link_to "消す", @tweet, method: :delete, data: { confirm: "本当に消しますか？"}, title: @tweet.tubuyaki %>
    </div>
    <div class="col-md-3">
      <div class="favorites">
        <%= link_to "#{@tweet.user_favorites.count}", favorites_tweet_path %>
        ☆
      </div>
    <% else %>
      <% if current_user.favorite?(@tweet) %>
        <%= form_for(current_user.favorite_relations.find_by(favorite_tweet_id: @tweet.id), html: { method: :delete } ) do |f| %>
        <%= f.submit "★", class: "btn btn-primary" %>
        <% end %>
      <% else %>
        <%= form_for(current_user.favorite_relations.build(favorite_tweet_id: @tweet.id)) do |f| %>
        <div> <%= f.hidden_field :favorite_tweet_id %> </div>
          <%= f.submit "☆", class: "btn  btn-primary" %>
        <% end %>
      <% end %>
      <%= link_to "#{@tweet.user_favorites.count}", favorites_tweet_path %>
    <% end %> -->
    <!-- </div>
    <%= link_to "リプライ", reply_tweet_path, class: "btn btn-primary" %>
    </div>
  </div> -->
  <div class="col-md-8">
    <% if @reply_tweets.any? %>
      <h2>リプライ</h2>
      <%= @reply_tweets.each do |tweet| %>
      <ul class="tweets">
        <%= render tweet %>
      </ul>
      <% end %>
    <% end %>
  </div>
</div>