config/routes.rb
Rails.application.routes.draw do
  resources 'users' do
    member do
      get :following, :followers, :favorites
    end
  end
  resources 'favorite_relations', only: [:create, :destroy]
  resources 'sessions', only: [:new, :create, :destroy]
  resources 'tweets' do
    member do
      get :favorites, :reply
    end
  end
  resources 'relationships', only: [:create, :destroy]

  root 'static_pages#home'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/search', to: 'tweets#search', via: 'get'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-error">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
  	<% object.errors.full_messages.each do |msg| %>
  	<li>*<%= msg %></li>
  	<% end %>
  </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<% @tweets = @feed_items %>
  <ul class="tweets">
    <%= render partial: '/tweets/tweet', collection: @tweets %>
  </ul>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <div>
    <% if feed_item.user.image? %>
    <%= image_tag feed_item.user.image.url(:thumb) %>
    <% else %>
    <%= image_tag("egg.png", width: "50", height: "50") %>
    <% end %>
  </div>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %> <small><%= feed_item.user.userid %></small>
  </span><br>
  <span class="tubuyaki"><%= wrap(simple_format(feed_item.tubuyaki)) %></span><br>
  <span>
  <% if feed_item.image.to_s.empty? %>
  <% else %>
  <%= link_to "image", feed_item.image.url.to_s, :'data-lightbox' => image_tag(feed_item.image_url) %>
  <% end %>
  </span>
  <span class="timestamp">
    <small>Tweeted <%= time_ago_in_words(feed_item.created_at) %> ago.</small>
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "消す", feed_item, method: :delete, data: { confirm: "本当に消しますか？"}, title: feed_item.tubuyaki %>
  <% else %>
    <% if current_user.favorite?(feed_item) %>
      <%= form_for(current_user.favorite_relations.find_by(favorite_tweet_id: feed_item.id), html: { method: :delete } ) do |f| %>
      <%= f.submit "★", class: "btn btn-primary" %>
      <% end %>
    <% else %>
      <%= form_for(current_user.favorite_relations.build(favorite_tweet_id: feed_item.id)) do |f| %>
      <div> <%= f.hidden_field :favorite_tweet_id %> </div>
        <%= f.submit "☆", class: "btn  btn-primary" %>
      <% end %>
    <% end %>
  <% end %>

</li>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href=" <%= following_user_path(@user) %>">
    フォロー
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
  </a>
  <a href=" <%= followers_user_path(@user) %>">
    フォロワー
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
  </a>
  <a href="<%= user_path(@user) %>">
    ツイート
    <strong id="tweets" class="stat">
      <%= @user.tweets.count %>
    </strong>
  </a>
  <a href="<%= favorites_user_path(@user) %>">
  お気に入り
  <strong id="favorites" class="stat">
    <%= @user.favorite_tweets.count %>
  </strong>
</a>
</div>

app/views/shared/_tweet_footer.html.erb
<div class="tweet-footer">
  <div class="favorite">
    <% if tweet.favorite?(tweet) %>
    <%= render 'unfavorite' %>
    <% else %>
    <%= render 'favorite' %>
    <% end %>
    <%= tweet.users.count %>
  </div>
  <% if current_user?(tweet.user) %>
    <%= link_to "消す", tweet, method: :delete, data: { confirm: "本当に消しますか？"}, title: tweet.tubuyaki %>
  <% end %>
</div>

app/views/shared/_tweet_form.html.erb
<%= form_for(@tweet) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
  <%= f.text_area :tubuyaki, placeholder: "今何してる？" %>
  <%= f.file_field :image %>
</div>
  <%= f.submit "つぶやく", class: "btn btn-large btn-primary"%>
<% end %>

app/views/shared/_tweet_header.html.erb
<div class="row">
  <div class="avator">

  </div>
  <span class="user">
    <%= link_to tweet.user.name, tweet.user %> <small> <%= tweet.user.userid %> </small>
  </span><br>
  <span class="timestamp">
    <small>Tweeted <%= time_ago_in_words(tweet.created_at) %> ago.</small>
  </span>
</div>

app/views/shared/_user_info.html.erb
<div class="user-info">
    <div>
      <% if @user.image? %>
          <%= image_tag @user.image.url(:thumb) %>
        <% else %>
          <%= image_tag("egg.png", width: "50", height: "50") %>
      <% end %>
    </div>
  <a href=" <%= user_path(@user) %>">
    <h2><%= @user.name %></h2>
  </a>
    <%= @user.userid %>
  <%= render '/shared/stats' %>
</div>