config/routes.rb
Rails.application.routes.draw do
  resources 'users' do
    member do
      get :following, :followers, :favorites
    end
  end
  resources 'favorite_relations', only: [:create, :destroy]
  resources 'sessions', only: [:new, :create, :destroy]
  resources 'tweets' do
    member do
      get :favorites, :reply
    end
  end
  resources 'relationships', only: [:create, :destroy]

  root 'static_pages#home'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/search', to: 'tweets#search', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include TweetsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<div>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to root_path, class: "navbar-brand icon-home" do %>
         <div>
         <span class="glyphicon glyphicon-home"></span>
         </div>
       <% end %>
      <!--<a class="navbar-brand" href="#"></a>-->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">さがす</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "ユーザーをさがす", users_path %></li>
        <li> <%= link_to "ツイート検索", tweets_path %> </li>
        <% if signed_in? %>
        <li><%= link_to "設定", edit_user_path(current_user.id) %></li>
        <li><%= link_to "ログアウト", signout_path, {method: :delete} %></li>
        <% else %>
        <li><%= link_to "ログイン", signin_path %></li>
        <li> <%= link_to "ユーザ登録", signup_path %></li>
        <% end %>
        <li> <%= link_to "Katatterについて", help_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>